'use strict';
const $ = s => document.querySelector(s);
const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
const stops = [
  ['Seúl','02–04 agosto','Corea','seul',37.5665,126.978,'Gwanghwamun y Olympic Park: los primeros días en Corea.'],
  ['Busan','05–07 agosto','Corea','busan',35.1796,129.0756,'Tres días en Busan, antes de regresar a Seúl.'],
  ['Seúl','08–09 agosto','Corea','gyeongbokgung',37.5665,126.978,'Namsan y Myeongdong, las últimas paradas en Corea.'],
  ['Tokio','10–13 agosto','Japón','tokyo',35.6762,139.6503,'Akihabara, Shibuya, Asakusa y Odaiba.'],
  ['Nagoya','14 agosto','Japón','14-0',35.1815,136.9066,'Una nueva parada en el recorrido por Japón.'],
  ['Kioto','15–16 agosto','Japón','kyoto',35.0116,135.7681,'Arashiyama y Fushimi Inari, dos días para recordar.'],
  ['Nara','17 agosto','Japón','17-0',34.6851,135.8048,'El capítulo de Nara en nuestro álbum.'],
  ['Hiroshima','18 agosto','Japón','hiroshima',34.3853,132.4553,'Las fotografías de un día en Hiroshima.'],
  ['Osaka','19–20 agosto','Japón','19-0',34.6937,135.5023,'Osaka y el día dedicado a Pokémon.'],
  ['Tokio','21–26 agosto','Japón','21-0',35.6762,139.6503,'Mitaka, Kamakura, Roppongi y los últimos días.']
].map(([name,date,country,photo,lat,lng,copy])=>({name,date,country,src:`assets/${photo}.webp`,lat,lng,copy}));
let map, route, traveler, routeIndex=0, routeFrame, routePlaying=false, routeElapsed=0, lastRouteTime=0;
$('#stops').innerHTML=stops.map((s,i)=>`<button data-stop="${i}" aria-pressed="${i===0}">${String(i+1).padStart(2,'0')} ${s.name}</button>`).join('');
function selectStop(i,pan=true){routeIndex=(i+stops.length)%stops.length;const s=stops[routeIndex];$('#stop-date').textContent=`${s.date.toUpperCase()} / ${s.country.toUpperCase()}`;$('#stop-title').textContent=s.name;$('#stop-photo').src=s.src;$('#stop-photo').alt=`${s.name}, ${s.date} de 2024`;$('#stop-copy').textContent=s.copy;document.querySelectorAll('[data-stop]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.stop)===routeIndex));if(map&&pan)map.panTo([s.lat,s.lng],{animate:!reduced});}
try{if(!window.L)throw Error('Mapa no disponible');map=L.map('map',{scrollWheelZoom:false}).setView([36,134],5);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);const coords=stops.map(s=>[s.lat,s.lng]);L.polyline(coords,{color:'#657d69',weight:2,opacity:.45,dashArray:'5 7'}).addTo(map);route=L.polyline([],{color:'#ba714b',weight:4}).addTo(map);stops.forEach((s,i)=>L.marker([s.lat,s.lng],{icon:L.divIcon({className:'map-marker',html:String(i+1),iconSize:[26,26]}),title:`${s.name}, ${s.date}`}).addTo(map).on('click',()=>{stopRoute();selectStop(i)}));traveler=L.circleMarker(coords[0],{radius:7,color:'#fff',weight:3,fillColor:'#ba714b',fillOpacity:1}).addTo(map);map.fitBounds(coords,{padding:[35,35]});$('#fit').onclick=()=>map.fitBounds(coords,{padding:[35,35]});}catch(e){$('#map').innerHTML='<p style="padding:30px">No se ha podido cargar el mapa. Puedes recorrer todas las paradas desde la lista.</p>';$('#fit').hidden=true;$('#route-play').disabled=true;}
selectStop(0,false);
function stopRoute(){routePlaying=false;cancelAnimationFrame(routeFrame);$('#route-play').textContent='▶ Animar ruta';}
function routeTick(time){if(!routePlaying)return;if(lastRouteTime)routeElapsed+=Math.min(time-lastRouteTime,100);lastRouteTime=time;const t=routeElapsed/2200,seg=Math.min(Math.floor(t),stops.length-2),fraction=Math.min(1,t-seg);const a=stops[seg],b=stops[seg+1],pos=[a.lat+(b.lat-a.lat)*fraction,a.lng+(b.lng-a.lng)*fraction];route.setLatLngs([...stops.slice(0,seg+1).map(s=>[s.lat,s.lng]),pos]);traveler.setLatLng(pos);if(routeIndex!==seg)selectStop(seg,false);if(t>=stops.length-1){selectStop(stops.length-1,false);stopRoute();routeElapsed=0;return;}routeFrame=requestAnimationFrame(routeTick);}
$('#route-play').onclick=()=>{if(routePlaying){stopRoute();return;}routePlaying=true;lastRouteTime=0;$('#route-play').textContent='Ⅱ Pausar ruta';$('#fit').click();routeFrame=requestAnimationFrame(routeTick);};
$('#stops').onclick=e=>{const b=e.target.closest('[data-stop]');if(b){stopRoute();selectStop(Number(b.dataset.stop));}};$('#route-prev').onclick=()=>{stopRoute();selectStop(routeIndex-1)};$('#route-next').onclick=()=>{stopRoute();selectStop(routeIndex+1)};
const chapters=[stops[0],stops[1],stops[3],stops[5],stops[7],stops[9]];
$('#story-steps').innerHTML=chapters.map((s,i)=>`<div class="story-step" data-chapter="${i}"><article><p class="eyebrow">${s.date.toUpperCase()} / ${s.country.toUpperCase()}</p><h3>${s.name}, en nuestro álbum.</h3><p>${s.copy}</p></article></div>`).join('');
const observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){const i=Number(e.target.dataset.chapter),s=chapters[i];$('#story-img').src=s.src;$('#story-img').alt=s.name;$('#story-name').textContent=s.name+'.';$('#story-date').textContent=`${s.date.toUpperCase()} / ${s.country.toUpperCase()}`;$('#story-counter').textContent=`0${i+1} / 06`;}},{rootMargin:'-35% 0px -35% 0px',threshold:0});document.querySelectorAll('.story-step').forEach(s=>observer.observe(s));
let scrollScheduled=false;window.addEventListener('scroll',()=>{if(scrollScheduled||reduced)return;scrollScheduled=true;requestAnimationFrame(()=>{const r=$('#historia').getBoundingClientRect();$('#story-img').style.setProperty('--story-scale',1.03+Math.min(.06,Math.max(0,-r.top/r.height*.06)));scrollScheduled=false;});},{passive:true});
let photos=[],filtered=[],page=0,viewIndex=0;
function renderBook(){const count=Math.ceil(filtered.length/4);page=Math.max(0,Math.min(page,count-1));$('#book').innerHTML=filtered.slice(page*4,page*4+4).map((p,i)=>`<button class="photo-card" data-photo="${page*4+i}" style="--rotation:${[-2,1,1.5,-1][i]}deg"><img src="${p.src}" alt="${p.place}, ${p.day} agosto 2024" loading="lazy"><small>${p.day} AGOSTO 2024</small><span>${p.place}</span></button>`).join('');$('#page-count').textContent=`${page+1} / ${count}`;$('#book-prev').disabled=page===0;$('#book-next').disabled=page===count-1;}
fetch('photos.json').then(r=>{if(!r.ok)throw Error('Album');return r.json()}).then(data=>{photos=data;filtered=photos;$('#photo-count').textContent=photos.length;renderBook();}).catch(()=>{$('#book').textContent='El álbum no se ha podido cargar. Recarga la página para volver a intentarlo.';});
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));filtered=photos.filter(p=>b.dataset.filter==='all'||(b.dataset.filter==='korea'?Number(p.day)<10:Number(p.day)>=10));page=0;renderBook();});$('#book-prev').onclick=()=>{page--;renderBook()};$('#book-next').onclick=()=>{page++;renderBook()};
function showPhoto(i){viewIndex=(i+filtered.length)%filtered.length;const p=filtered[viewIndex];$('#viewer-img').src=p.src;$('#viewer-img').alt=`${p.place}, ${p.day} agosto 2024`;$('#viewer-caption').textContent=`${p.place} · ${p.day} agosto 2024 · ${viewIndex+1}/${filtered.length}`;}
$('#book').onclick=e=>{const b=e.target.closest('[data-photo]');if(b){showPhoto(Number(b.dataset.photo));$('#viewer').showModal();}};$('#viewer-prev').onclick=()=>showPhoto(viewIndex-1);$('#viewer-next').onclick=()=>showPhoto(viewIndex+1);$('#viewer-close').onclick=()=>$('#viewer').close();
let cinemaPhotos=[],cinemaIndex=0,cinemaTimer,playing=false,slideElapsed=0,lastTick=0;const slideDuration=6000;
$('#cinema-next').setAttribute('aria-label','Siguiente foto');$('#cinema-prev').setAttribute('aria-label','Foto anterior');$('#cinema-progress').setAttribute('aria-label','Progreso: 100 fotos');
function renderProgress(){const rail=$('#cinema-progress');rail.innerHTML=cinemaPhotos.map((p,i)=>`<button type="button" data-slide="${i}" aria-label="Ir a la foto ${i+1} de 100" aria-current="${i===cinemaIndex}" class="${i<cinemaIndex?'done':''}" style="--fill:${i<cinemaIndex?100:i===cinemaIndex?Math.round(slideElapsed/slideDuration*100):0}%"></button>`).join('');}
function updateProgress(){const buttons=$('#cinema-progress').children;for(let i=0;i<buttons.length;i++){buttons[i].style.setProperty('--fill',i<cinemaIndex?'100%':i===cinemaIndex?`${Math.min(100,slideElapsed/slideDuration*100)}%`:'0%');buttons[i].classList.toggle('done',i<cinemaIndex);buttons[i].setAttribute('aria-current',String(i===cinemaIndex));}}
function cinemaScene(i,reset=true){cinemaIndex=Math.max(0,Math.min(i,cinemaPhotos.length-1));if(reset)slideElapsed=0;const p=cinemaPhotos[cinemaIndex];$('#cinema-img').src=p.src;$('#cinema-img').alt=`${p.place}, ${p.day} de agosto de 2024`;$('#cinema-img').style.animation='none';void $('#cinema-img').offsetWidth;$('#cinema-img').style.animation='';$('#cinema-date').textContent=`${p.day} AGOSTO 2024 / RECUERDO ${String(cinemaIndex+1).padStart(2,'0')} DE 100`;$('#cinema-title').textContent=p.place+'.';$('#cinema-text').textContent='Un instante de nuestro viaje que merece quedarse un poco más.';$('#cinema-count').textContent=`${cinemaIndex+1} / 100`;$('#cinema-prev').disabled=cinemaIndex===0;$('#cinema-next').disabled=cinemaIndex===cinemaPhotos.length-1;renderProgress();const active=$(`#cinema-progress [data-slide="${cinemaIndex}"]`);if(active)active.scrollIntoView({block:'nearest',inline:'nearest'});}
function cinemaTick(time){if(!playing)return;if(lastTick)slideElapsed+=Math.min(time-lastTick,100);lastTick=time;if(slideElapsed>=slideDuration){if(cinemaIndex>=cinemaPhotos.length-1){playing=false;$('#cinema-pause').textContent='Repetir';slideElapsed=slideDuration;updateProgress();return;}cinemaScene(cinemaIndex+1);}else updateProgress();cinemaTimer=requestAnimationFrame(cinemaTick);}
function setPlaying(value){playing=value;$('#cinema-pause').textContent=playing?'Pausar':cinemaIndex===cinemaPhotos.length-1?'Repetir':'Reproducir';lastTick=0;cancelAnimationFrame(cinemaTimer);if(playing)cinemaTimer=requestAnimationFrame(cinemaTick);}
$('#cinema-progress').onclick=e=>{const b=e.target.closest('[data-slide]');if(b){cinemaScene(Number(b.dataset.slide));setPlaying(true);}};
document.querySelectorAll('.play-trigger').forEach(b=>b.onclick=()=>{stopRoute();if(!cinemaPhotos.length)return;cinemaScene(0);$('#cinema').showModal();setPlaying(!reduced);});$('#cinema-pause').onclick=()=>{if(!playing&&cinemaIndex===cinemaPhotos.length-1)cinemaScene(0);setPlaying(!playing)};$('#cinema-prev').onclick=()=>{cinemaScene(cinemaIndex-1);setPlaying(true)};$('#cinema-next').onclick=()=>{cinemaScene(cinemaIndex+1);setPlaying(true)};$('#cinema-close').onclick=()=>$('#cinema').close();$('#cinema').addEventListener('close',()=>setPlaying(false));
document.addEventListener('keydown',e=>{if($('#viewer').open){if(e.key==='ArrowRight')showPhoto(viewIndex+1);if(e.key==='ArrowLeft')showPhoto(viewIndex-1);}else if($('#cinema').open){if(e.key==='ArrowRight')$('#cinema-next').click();if(e.key==='ArrowLeft')$('#cinema-prev').click();if(e.key===' '){e.preventDefault();$('#cinema-pause').click();}}});
const depth=$('#depth'),card=$('.depth-card');function tilt(e){if(reduced)return;const r=depth.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.setProperty('--rx',`${-y*9}deg`);card.style.setProperty('--ry',`${x*10}deg`);card.style.setProperty('--gx',`${(x+.5)*100}%`);card.style.setProperty('--gy',`${(y+.5)*100}%`);}depth.addEventListener('pointermove',tilt);function resetTilt(){card.style.setProperty('--rx','0deg');card.style.setProperty('--ry','0deg');}depth.addEventListener('pointerleave',resetTilt);depth.addEventListener('pointerup',resetTilt);
fetch('photos.json').then(r=>r.json()).then(data=>{cinemaPhotos=data.slice(0,100);}).catch(()=>{});
